apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-runner
  namespace: onlinebookstore
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader-onlinebookstore-role
  namespace: onlinebookstore
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-onlinebookstore-rolebinding
  namespace: onlinebookstore
roleRef:
  kind: Role
  name: pod-reader-onlinebookstore-role
subjects:
  - kind: ServiceAccount
    name: kubectl-runner
    namespace: onlinebookstore

