apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: mongodb
  namespace: onlinebookstore
spec:
  replicas: 2
  serviceName: bookstore-mongodb
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels: 
        app: mongo
    spec:
      containers: 
      - name: bs-mongodb
        image: mongo:8.2.5
        command:
          - mongod
          - "--replSet"
          - rs0
          - "--bind_ip_all"
        ports:
          - containerPort: 27017
            name: mongodb
        volumeMounts:
          - name: mongodb-persistent-data
            mountPath: /data/db
  volumeClaimTemplates: 
    - metadata:
        name: mongodb-persistent-data
        namespace: onlinebookstore
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi 