FROM node:24 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine AS nginx-server

RUN rm /etc/nginx/conf.d/default.conf

COPY ./config/nginx.conf.template /etc/nginx/templates/default.conf.template

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]