FROM node:24 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# ENV BACKEND_HOST=bookstore-backend
# ENV PORT=3000

EXPOSE 3000

CMD ["npm", "start"]

# RUN npm run build

# FROM nginx:alpine AS nginx-server

# # Remove default nginx config
# RUN rm /etc/nginx/conf.d/default.conf

# # Copy custom nginx config
# COPY ./config/nginx.conf /etc/nginx/nginx.conf

# COPY --from=build /app/build /usr/share/nginx/html

# EXPOSE 80

# CMD ["nginx", "-g", "daemon off;"]